# Generated by Django 6.1.1 on 2026-10-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pet_age_alter_pet_walk_times_alter_staff_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In_progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('total_price', models.IntegerField()),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='core.pet')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff', to='core.staff')),
            ],
        ),
    ]
