# Generated by Django 6.1.1 on 2026-10-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_pet_id_booking_pet_remove_booking_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'Animal type', 'verbose_name_plural': 'Animal types'},
        ),
    ]
